
package com.legstar.test.cixs.fixarsim;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "FixarsimFaultInfo", targetNamespace = "http://cixs.test.legstar.com/fixarsim")
public class FixarsimFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FixarsimFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FixarsimFault(String message, FixarsimFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FixarsimFault(String message, FixarsimFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.fixarsim.FixarsimFaultInfo
     */
    public FixarsimFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
