
package com.legstar.test.cixs.floatmix;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "FloatmixFaultInfo", targetNamespace = "http://cixs.test.legstar.com/floatmix")
public class FloatmixFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FloatmixFaultInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FloatmixFault(String message, FloatmixFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FloatmixFault(String message, FloatmixFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.floatmix.FloatmixFaultInfo
     */
    public FloatmixFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
