
package com.legstar.test.cixs.fixarcom;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "fixarcomService", targetNamespace = "http://cixs.test.legstar.com/fixarcom", wsdlLocation = "http://localhost:8080/cixs-fixarcom/fixarcom?wsdl")
public class FixarcomService
    extends Service
{

    private final static URL FIXARCOMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.legstar.test.cixs.fixarcom.FixarcomService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.legstar.test.cixs.fixarcom.FixarcomService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/cixs-fixarcom/fixarcom?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/cixs-fixarcom/fixarcom?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FIXARCOMSERVICE_WSDL_LOCATION = url;
    }

    public FixarcomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FixarcomService() {
        super(FIXARCOMSERVICE_WSDL_LOCATION, new QName("http://cixs.test.legstar.com/fixarcom", "fixarcomService"));
    }

    /**
     * 
     * @return
     *     returns FixarcomPort
     */
    @WebEndpoint(name = "fixarcomPort")
    public FixarcomPort getFixarcomPort() {
        return super.getPort(new QName("http://cixs.test.legstar.com/fixarcom", "fixarcomPort"), FixarcomPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FixarcomPort
     */
    @WebEndpoint(name = "fixarcomPort")
    public FixarcomPort getFixarcomPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cixs.test.legstar.com/fixarcom", "fixarcomPort"), FixarcomPort.class, features);
    }

}
