package com.legstar.test.cixs;


import junit.framework.TestCase;

/**
 * Generic code common to all test cases.
 *
 */
public abstract class AbstractOperationCases extends TestCase {

    /** Cobol binding classes package. As generated by LegStar Coxbgen. */
    public static final String JAXB_PKG_PREFIX = "com.legstar.test.coxb";


}
