/*******************************************************************************
 *  LegStar legacy Web-enablement .
 *  Copyright (C) 2007 LegSem
 *  
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *   
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 *  02110-1301  USA
 *  
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.26 at 06:16:45 PM CET 
//


package com.legstar.test.coxb.binpkdus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolType;
import com.legstar.coxb.annotation.CobolElement;


/**
 * <p>Java class for WsUnsignedPackedDecimalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WsUnsignedPackedDecimalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WsCompat" type="{http://legstar.com/test/coxb/binpkdus}WsCompatType"/>
 *         &lt;element name="WsExtend" type="{http://legstar.com/test/coxb/binpkdus}WsExtendType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WsUnsignedPackedDecimalType", propOrder = {
    "wsCompat",
    "wsExtend"
})
public class WsUnsignedPackedDecimalType {

    @XmlElement(name = "WsCompat", required = true)
    @CobolElement(cobolName = "WS-COMPAT", type = CobolType.GROUP_ITEM, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected WsCompatType wsCompat;
    @XmlElement(name = "WsExtend", required = true)
    @CobolElement(cobolName = "WS-EXTEND", type = CobolType.GROUP_ITEM, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected WsExtendType wsExtend;

    /**
     * Gets the value of the wsCompat property.
     * 
     * @return
     *     possible object is
     *     {@link WsCompatType }
     *     
     */
    public WsCompatType getWsCompat() {
        return wsCompat;
    }

    /**
     * Sets the value of the wsCompat property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsCompatType }
     *     
     */
    public void setWsCompat(WsCompatType value) {
        this.wsCompat = value;
    }

    public boolean isSetWsCompat() {
        return (this.wsCompat!= null);
    }

    /**
     * Gets the value of the wsExtend property.
     * 
     * @return
     *     possible object is
     *     {@link WsExtendType }
     *     
     */
    public WsExtendType getWsExtend() {
        return wsExtend;
    }

    /**
     * Sets the value of the wsExtend property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsExtendType }
     *     
     */
    public void setWsExtend(WsExtendType value) {
        this.wsExtend = value;
    }

    public boolean isSetWsExtend() {
        return (this.wsExtend!= null);
    }

}
