
package com.legstar.test.cixs.lsfileac;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.legstar.test.coxb.lsfileac.ReplyStatusType;
		
import com.legstar.test.coxb.lsfileac.ReplyDataType;
		

/**
 * Response holder element.
 * 
 * This class was generated by CIXS generator.
 * 2007-07-26T14:36:57.343+02:00
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LsfileacResponseHolder",
         namespace = "http://cixs.test.legstar.com/lsfileac",
         propOrder = {

    "replyStatus",
    "replyData"
})
public class LsfileacResponseHolder {
	

    /** Inner ReplyStatusType JAXB-bound object. */
    @XmlElement(name = "replyStatus",
                namespace = "http://cixs.test.legstar.com/lsfileac",
                required = true)
    private ReplyStatusType replyStatus;
		
    /** Inner ReplyDataType JAXB-bound object. */
    @XmlElement(name = "replyData",
                namespace = "http://cixs.test.legstar.com/lsfileac",
                required = true)
    private ReplyDataType replyData;
		
	/**
	 * Get the inner ReplyStatusType JAXB-bound object.
	 * 
	 * @return JAXB-bound object
	 */
	public final ReplyStatusType getReplyStatus() {
		return replyStatus;
	}

	/**
	 * Set the inner ReplyStatusType JAXB-bound object.
	 * 
	 * @param value JAXB-bound object
	 */
	public final void setReplyStatus(
	    final ReplyStatusType value) {
		this.replyStatus = value;
	}
		
	/**
	 * Get the inner ReplyDataType JAXB-bound object.
	 * 
	 * @return JAXB-bound object
	 */
	public final ReplyDataType getReplyData() {
		return replyData;
	}

	/**
	 * Set the inner ReplyDataType JAXB-bound object.
	 * 
	 * @param value JAXB-bound object
	 */
	public final void setReplyData(
	    final ReplyDataType value) {
		this.replyData = value;
	}
		
}
