
package com.legstar.test.cixs.lsfileac;
import javax.xml.ws.WebFault;

/**
 * Fault element used as return message when an exception occurs.
 * 
 * This class was generated by CIXS generator.
 * 2007-07-09T13:01:37.953+02:00
 */

@WebFault(name = "LsfileacFaultInfo",
          targetNamespace = "http://cixs.test.legstar.com/lsfileac")
public class LsfileacFault
    extends Exception {

    /** Default serialVersionUID.  */
	private static final long serialVersionUID = 1L;
	
    /** Java type that goes as soapenv:Fault detail element. */
    private LsfileacFaultInfo faultInfo;

    /**
     * Constructor for Web Fault.
     * @param fault error details
     * @param message error summary
     */
    public LsfileacFault(
    	final String message,
    	final LsfileacFaultInfo fault) {
    	
        super(message);
        this.faultInfo = fault;
    }

    /**
     * Constructor for Web Fault with cause.
     * @param fault error details
     * @param message error summary
     * @param cause the cause
     */
    public LsfileacFault(
        final String message,
        final LsfileacFaultInfo fault,
        final Throwable cause) {
        
        super(message, cause);
        this.faultInfo = fault;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.lsfileac.LsfileacFaultInfo
     */
    public final LsfileacFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
