


package com.legstar.test.coxb.MSNSearch.bind;

import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.ICobolBinaryBinding;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.test.coxb.MSNSearch.SearchResponseType;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.legstar.test.coxb.MSNSearch.SearchResponse;
import com.legstar.test.coxb.MSNSearch.ObjectFactory;

/**
 * LegStar Binding for Complex element :
 *   SearchResponse.
 * 
 * This class was generated by LegStar Binding generator.
 */
public class SearchResponseBinding 
             extends CComplexBinding {

    /** Value object to which this cobol complex element is bound. */
    private SearchResponse mValueObject;
  
    /** Indicates that the associated Value object just came from the constructor
     * and doesn't need to be recreated. */
    private boolean mUnusedValueObject = false;
    
    /** Maximum host bytes size for this complex object. */
    private static final int BYTE_LENGTH = 181932;
    
    /** Unbound child. */
    public ICobolBinaryBinding _searchTagWrapperCounter;
    /** Unbound child. */
    public ICobolBinaryBinding _resultWrapperCounter;
    /** Unbound child. */
    public ICobolBinaryBinding _sourceResponseWrapperCounter;
    /** Child bound to value object property Response(SearchResponseType). */
    public ICobolComplexBinding _response;
            
    /** Logger. */
    private final Log _log = LogFactory.getLog(getClass());

    /** Binding factory. */
    private static final ICobolBindingFactory BF
        = CobolBindingFactory.getBindingFactory();
 
    /** Static reference to Value object factory to be used as default. */
    private static final ObjectFactory JF = new ObjectFactory();
    
    /** Current Value object factory (Defaults to the static one but can be
     *  changed). */
    private ObjectFactory mValueObjectFactory = JF;
    
    /**
     * Constructor for a root Complex element without a bound Value object.
     */
    public SearchResponseBinding() {
        this(null);
    }

    /**
     * Constructor for a root Complex element with a bound Value object.
     * 
     * @param valueObject the concrete Value object instance bound to this
     *        complex element
     */
    public SearchResponseBinding(
            final SearchResponse valueObject) {
        this("", "", null, valueObject);
    }

    /**
    * Constructor for a Complex element as a child of another element and
    * an associated Value object.
    * 
    * @param bindingName the identifier for this binding
    * @param fieldName field name in parent Value object
    * @param valueObject the concrete Value object instance bound to this
    *        complex element
    * @param parentBinding a reference to the parent binding
    */
    public SearchResponseBinding(
            final String bindingName,
            final String fieldName,
            final ICobolComplexBinding parentBinding,
            final SearchResponse valueObject) {
        
        super(bindingName, fieldName, SearchResponse.class, null, parentBinding);
        mValueObject = valueObject;
        if (mValueObject != null) {
            mUnusedValueObject = true;
        }
        initChildren();
        setByteLength(BYTE_LENGTH);
    }

    /** Creates a binding property for each child. */
    private void initChildren() {
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing started");
        }
        /* Create binding children instances */

        _searchTagWrapperCounter = BF.createBinaryBinding("SearchTagWrapperCounter",
               this);
        _searchTagWrapperCounter.setCobolName("SearchTag--C");
        _searchTagWrapperCounter.setByteLength(4);
        _searchTagWrapperCounter.setTotalDigits(9);
        _searchTagWrapperCounter.setIsODOObject(true);
        _resultWrapperCounter = BF.createBinaryBinding("ResultWrapperCounter",
               this);
        _resultWrapperCounter.setCobolName("Result--C");
        _resultWrapperCounter.setByteLength(4);
        _resultWrapperCounter.setTotalDigits(9);
        _resultWrapperCounter.setIsODOObject(true);
        _sourceResponseWrapperCounter = BF.createBinaryBinding("SourceResponseWrapperCounter",
               this);
        _sourceResponseWrapperCounter.setCobolName("SourceResponse--C");
        _sourceResponseWrapperCounter.setByteLength(4);
        _sourceResponseWrapperCounter.setTotalDigits(9);
        _sourceResponseWrapperCounter.setIsODOObject(true);
        _response = new SearchResponseTypeBinding("Response",
               "Response", this, null);
        _response.setCobolName("Response");
        _response.setByteLength(181920);

        /* Add children to children list */
        storeCounter(_searchTagWrapperCounter);
        storeCounter(_resultWrapperCounter);
        storeCounter(_sourceResponseWrapperCounter);
        getChildrenList().add(_response);
 
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing successful");
        }
    }
    
    /** {@inheritDoc} */
    public void createValueObject() throws HostException {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
        if (mUnusedValueObject && mValueObject != null) {
            mUnusedValueObject = false;
            return;
        }
        mValueObject = mValueObjectFactory.createSearchResponse();
    }

    /** {@inheritDoc} */
    public void setChildrenValues() throws HostException {

         /* Make sure there is an associated Value object*/
        if (mValueObject == null) {
            createValueObject();
        }
        /* Get Value object property _response */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_response"
                    + " value=" + mValueObject.getResponse());
        }
        _response.setObjectValue(mValueObject.getResponse());
     }

    /** {@inheritDoc} */
    public void setPropertyValue(final int index) throws HostException {
 
        ICobolBinding child = getChildrenList().get(index);
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
        if (!child.isBound()) {
            return;
        }
        
        /* Set the Value object property value from binding object */
        Object bindingValue = null;
        switch (index) {
        case 0:
            break;
        case 1:
            break;
        case 2:
            break;
        case 3:
            bindingValue = child.getObjectValue(SearchResponseType.class);
            mValueObject.setResponse((SearchResponseType) bindingValue);
            break;
         default:
            break;
        }
        if (_log.isDebugEnabled()) {
            _log.debug("Setting value of Value object property "
                    + child.getJaxbName()
                    + " value=" + bindingValue);
        }
    }

    /** {@inheritDoc} */
    public Object getObjectValue(
            final Class < ? > type) throws HostException {
        if (type.equals(SearchResponse.class)) {
            return mValueObject;
        } else {
            throw new HostException("Attempt to get binding " + getBindingName()
                    + " as an incompatible type " + type);
        }
    }

    /** {@inheritDoc} */
    public void setObjectValue(
            final Object bindingValue) throws HostException {
        if (bindingValue == null) {
            mValueObject = null;
            return;
        }
        if (bindingValue.getClass().equals(SearchResponse.class)) {
            mValueObject = (SearchResponse) bindingValue;
        } else {
            throw new HostException("Attempt to set binding " + getBindingName()
                    + " from an incompatible value " + bindingValue);
        }
    }

    /**
     * @return the java object factory for objects creation
     */
    public ObjectFactory getObjectFactory() {
        return mValueObjectFactory;
    }

    /**
     * @param valueObjectFactory the java object factory for objects creation 
     */
    public void setObjectFactory(final Object valueObjectFactory) {
        mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

    /** {@inheritDoc} */
    public boolean isSet() {
        return (mValueObject != null);
    }

    /**
     * @return the bound Value object
     */
    public SearchResponse getSearchResponse() {
        return mValueObject;
    }
    
    /**
     * The COBOL complex element maximum length in bytes.
     * 
     * @return COBOL complex element maximum length in bytes
     */
    public int getByteLength() {
        return BYTE_LENGTH;
    }
}

