
package com.legstar.test.cixs.typesmix;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TypesmixFaultInfo", targetNamespace = "http://cixs.test.legstar.com/typesmix")
public class TypesmixFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TypesmixFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TypesmixFault(String message, TypesmixFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TypesmixFault(String message, TypesmixFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.typesmix.TypesmixFaultInfo
     */
    public TypesmixFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
