
package com.legstar.test.cixs.typesmix;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "typesmixService", targetNamespace = "http://cixs.test.legstar.com/typesmix", wsdlLocation = "http://localhost:8080/cixs-typesmix/typesmix?wsdl")
public class TypesmixService
    extends Service
{

    private final static URL TYPESMIXSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.legstar.test.cixs.typesmix.TypesmixService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.legstar.test.cixs.typesmix.TypesmixService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/cixs-typesmix/typesmix?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/cixs-typesmix/typesmix?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TYPESMIXSERVICE_WSDL_LOCATION = url;
    }

    public TypesmixService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TypesmixService() {
        super(TYPESMIXSERVICE_WSDL_LOCATION, new QName("http://cixs.test.legstar.com/typesmix", "typesmixService"));
    }

    /**
     * 
     * @return
     *     returns TypesmixPort
     */
    @WebEndpoint(name = "typesmixPort")
    public TypesmixPort getTypesmixPort() {
        return super.getPort(new QName("http://cixs.test.legstar.com/typesmix", "typesmixPort"), TypesmixPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TypesmixPort
     */
    @WebEndpoint(name = "typesmixPort")
    public TypesmixPort getTypesmixPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cixs.test.legstar.com/typesmix", "typesmixPort"), TypesmixPort.class, features);
    }

}
