
package com.legstar.test.cixs.lsfileac;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lsfileacPort", targetNamespace = "http://cixs.test.legstar.com/lsfileac")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.cixs.lsfileac.ObjectFactory.class,
    com.legstar.test.coxb.lsfileac.ObjectFactory.class
})
public interface LsfileacPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.lsfileac.LsfileacResponse
     * @throws LsfileacFault
     */
    @WebMethod(action = "urn:lsfileac")
    @WebResult(name = "LsfileacResponse", targetNamespace = "http://cixs.test.legstar.com/lsfileac", partName = "result")
    public LsfileacResponse lsfileac(
        @WebParam(name = "LsfileacRequest", targetNamespace = "http://cixs.test.legstar.com/lsfileac", partName = "parameters")
        LsfileacRequest parameters,
        @WebParam(name = "LsfileacHostHeader", targetNamespace = "http://cixs.test.legstar.com/lsfileac", header = true, partName = "hostHeader")
        LsfileacHostHeader hostHeader)
        throws LsfileacFault
    ;

}
