


package com.legstar.test.coxb.dplarcht.bind;

import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.ICobolBinaryBinding;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolChoiceBinding;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.test.coxb.dplarcht.LsSearchCriteria;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.legstar.test.coxb.dplarcht.LsRequest;
import com.legstar.test.coxb.dplarcht.ObjectFactory;

/**
 * LegStar Binding for Complex element :
 *   LsRequest.
 * 
 * This class was generated by LegStar Binding generator.
 */
public class LsRequestBinding 
             extends CComplexBinding {

    /** Value object to which this cobol complex element is bound. */
    private LsRequest mValueObject;
  
    /** Indicates that the associated Value object just came from the constructor
     * and doesn't need to be recreated. */
    private boolean mUnusedValueObject = false;
    
    /** Maximum host bytes size for this complex object. */
    public static final int BYTE_LENGTH = 19;
    
    /** Child bound to value object property LsRequestType(Integer). */
    public ICobolBinaryBinding _lsRequestType;
    /** Unbound child. */
    public ICobolChoiceBinding _lsAllItemsChoice;
    /** Child bound to value object property LsSearchCriteria(LsSearchCriteria). */
    public ICobolComplexBinding _lsSearchCriteria;
            
    /** Logger. */
    private final Log _log = LogFactory.getLog(getClass());

    /** Binding factory. */
    private static final ICobolBindingFactory BF
        = CobolBindingFactory.getBindingFactory();
 
    /** Static reference to Value object factory to be used as default. */
    private static final ObjectFactory JF = new ObjectFactory();
    
    /** Current Value object factory (Defaults to the static one but can be
     *  changed). */
    private ObjectFactory mValueObjectFactory = JF;
    
    /**
     * Constructor for a root Complex element without a bound Value object.
     */
    public LsRequestBinding() {
        this(null);
    }

    /**
     * Constructor for a root Complex element with a bound Value object.
     * 
     * @param valueObject the concrete Value object instance bound to this
     *        complex element
     */
    public LsRequestBinding(
            final LsRequest valueObject) {
        this("", "", null, valueObject);
    }

    /**
    * Constructor for a Complex element as a child of another element and
    * an associated Value object.
    * 
    * @param bindingName the identifier for this binding
    * @param fieldName field name in parent Value object
    * @param valueObject the concrete Value object instance bound to this
    *        complex element
    * @param parentBinding a reference to the parent binding
    */
    public LsRequestBinding(
            final String bindingName,
            final String fieldName,
            final ICobolComplexBinding parentBinding,
            final LsRequest valueObject) {
        
        super(bindingName, fieldName, LsRequest.class, null, parentBinding);
        mValueObject = valueObject;
        if (mValueObject != null) {
            mUnusedValueObject = true;
        }
        initChildren();
        setByteLength(BYTE_LENGTH);
    }

    /** Creates a binding property for each child. */
    private void initChildren() {
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing started");
        }
        /* Create binding children instances */

        _lsRequestType = BF.createBinaryBinding("LsRequestType",
               "LsRequestType", Integer.class, this);
        _lsRequestType.setCobolName("LS-REQUEST-TYPE");
        _lsRequestType.setByteLength(2);
        _lsRequestType.setTotalDigits(4);
        _lsRequestType.setIsCustomVariable(true);
        _lsAllItemsChoice = new LsAllItemsChoiceBinding("LsAllItemsChoice", this);
        _lsAllItemsChoice.setCobolName("LS-ALL-ITEMS");
        _lsAllItemsChoice.setByteLength(4);
        _lsSearchCriteria = new LsSearchCriteriaBinding("LsSearchCriteria",
               "LsSearchCriteria", this, null);
        _lsSearchCriteria.setCobolName("LS-SEARCH-CRITERIA");
        _lsSearchCriteria.setByteLength(13);

        /* Add children to children list */
        getChildrenList().add(_lsRequestType);
        getChildrenList().add(_lsAllItemsChoice);
        getChildrenList().add(_lsSearchCriteria);
 
        if (_log.isDebugEnabled()) {
            _log.debug("Initializing successful");
        }
    }
    
    /** {@inheritDoc} */
    public void createValueObject() throws HostException {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
        if (mUnusedValueObject && mValueObject != null) {
            mUnusedValueObject = false;
            return;
        }
        mValueObject = mValueObjectFactory.createLsRequest();
    }

    /** {@inheritDoc} */
    public void setChildrenValues() throws HostException {

         /* Make sure there is an associated Value object*/
        if (mValueObject == null) {
            createValueObject();
        }
        /* Get Value object property _lsRequestType */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_lsRequestType"
                    + " value=" + mValueObject.getLsRequestType());
        }
        _lsRequestType.setObjectValue(mValueObject.getLsRequestType());
        /* Get Value object property _lsSearchCriteria */
        if (_log.isDebugEnabled()) {
            _log.debug("Getting value from Value object property "
                    + "_lsSearchCriteria"
                    + " value=" + mValueObject.getLsSearchCriteria());
        }
        _lsSearchCriteria.setObjectValue(mValueObject.getLsSearchCriteria());
     }

    /** {@inheritDoc} */
    public void setPropertyValue(final int index) throws HostException {
 
        ICobolBinding child = getChildrenList().get(index);
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
        if (!child.isBound()) {
            return;
        }
        
        /* Set the Value object property value from binding object */
        Object bindingValue = null;
        switch (index) {
        case 0:
            bindingValue = child.getObjectValue(Integer.class);
            mValueObject.setLsRequestType((Integer) bindingValue);
            break;
        case 1:
            break;
        case 2:
            bindingValue = child.getObjectValue(LsSearchCriteria.class);
            mValueObject.setLsSearchCriteria((LsSearchCriteria) bindingValue);
            break;
         default:
            break;
        }
        if (_log.isDebugEnabled()) {
            _log.debug("Setting value of Value object property "
                    + child.getJaxbName()
                    + " value=" + bindingValue);
        }
    }

    /** {@inheritDoc} */
    public Object getObjectValue(
            final Class < ? > type) throws HostException {
        if (type.equals(LsRequest.class)) {
            return mValueObject;
        } else {
            throw new HostException("Attempt to get binding " + getBindingName()
                    + " as an incompatible type " + type);
        }
    }

    /** {@inheritDoc} */
    public void setObjectValue(
            final Object bindingValue) throws HostException {
        if (bindingValue == null) {
            mValueObject = null;
            return;
        }
        if (bindingValue.getClass().equals(LsRequest.class)) {
            mValueObject = (LsRequest) bindingValue;
        } else {
            throw new HostException("Attempt to set binding " + getBindingName()
                    + " from an incompatible value " + bindingValue);
        }
    }

    /**
     * @return the java object factory for objects creation
     */
    public ObjectFactory getObjectFactory() {
        return mValueObjectFactory;
    }

    /**
     * @param valueObjectFactory the java object factory for objects creation 
     */
    public void setObjectFactory(final Object valueObjectFactory) {
        mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

    /** {@inheritDoc} */
    public boolean isSet() {
        return (mValueObject != null);
    }

    /**
     * @return the bound Value object
     */
    public LsRequest getLsRequest() {
        return mValueObject;
    }
    
    /**
     * The COBOL complex element maximum length in bytes.
     * 
     * @return COBOL complex element maximum length in bytes
     */
    public int getByteLength() {
        return BYTE_LENGTH;
    }
}

