package com.legstar.test.cixs.fixarsim;
import java.rmi.server.UID;
import javax.jws.WebService;

import com.legstar.coxb.transform.HostTransformException;
import com.legstar.host.invoke.AbstractServiceAdapter;
import com.legstar.host.invoke.HostInvokerException;
import com.legstar.messaging.LegStarAddress;
import com.legstar.test.coxb.fixarsim.Dfhcommarea;

/**
 * JAX-WS Service Adapter implementation.
 * Each method maps to a CICS program. 
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */
@WebService(endpointInterface = "com.legstar.test.cixs.fixarsim.Fixarsim",
            serviceName = "fixarsimService",
            portName = "fixarsimPort",
            targetNamespace = "http://cixs.test.legstar.com/fixarsim")
public class FixarsimImpl extends AbstractServiceAdapter implements Fixarsim {

    /** Name of this service adapter implementation. */
    private static final String  SERVICE_ADAPTER_NAME = "fixarsim";

    /** Invoker implementation for operation fixarsim. */
    private FixarsimProgramInvoker mFixarsimProgramInvoker;

    /** Contructor creates a set of operation invokers. */
    public FixarsimImpl() {
        super(SERVICE_ADAPTER_NAME);
        mFixarsimProgramInvoker = new FixarsimProgramInvoker(getConfigFileName());
    }
    
    /** {@inheritDoc} */
    public Dfhcommarea fixarsim(
               final Dfhcommarea request,
               final FixarsimHostHeader hostHeader)
               throws FixarsimFault {
    
        try {
            return getFixarsimProgramInvoker().fixarsim(
                    getAddress(hostHeader), getRequestID(hostHeader), request);
        } catch (HostInvokerException e) {
            throw getFixarsimFault(e, "Failed to invoke host program:");
        } catch (HostTransformException e) {
            throw getFixarsimFault(e, "Failed to transform data:");
        }
    }

    /**
     * Formats a fault element to notify client of an exception.
     *
     * @param e the exception which occurred
     * @param text short message describing the context
     * @return the fault exception
     */
    public FixarsimFault getFixarsimFault(
            final Exception e, final String text) {

        FixarsimFaultInfo faultInfo = new FixarsimFaultInfo();
        faultInfo.setMessage(e.getMessage());
        faultInfo.setDetail(getFixarsimProgramInvoker().toString());
        return new FixarsimFault(text + ' ' 
                + faultInfo.getMessage(), faultInfo, e);
    }

        
    /**
     * Extracts header data from SOAP header and create a host address.
     * @param hostHeader the java object mapping the SOAP header element
     * @return the new host address
     */
    public LegStarAddress getAddress(
            final FixarsimHostHeader hostHeader) {
        if (hostHeader == null) {
            return null;
        }
        LegStarAddress address = new LegStarAddress(hostHeader.getHostEndPoint());
        address.setHostCharset(hostHeader.getHostCharset());
        address.setHostUserID(hostHeader.getHostUserID());
        address.setHostPassword(hostHeader.getHostPassword());
        address.setHostTraceMode(hostHeader.getHostTraceMode());
        return address;
    }

    /**
     * Generates a unique ID for a request. This can be passed from the client
     * using the host header.
     * @param hostHeader the java object mapping the SOAP header element
     * @return  a unique request ID
     */
    public String getRequestID(final FixarsimHostHeader hostHeader) {
        if (hostHeader != null && hostHeader.getHostRequestID() != null) {
            return hostHeader.getHostRequestID();
        } else {
            return getServiceAdapterName() + ":" + new UID().toString();
        }
    }

    /**
     * @return the invoker implementation for operation fixarsim
     */
    public FixarsimProgramInvoker getFixarsimProgramInvoker() {
        return mFixarsimProgramInvoker;
    }

    /**
     * @param programInvoker the invoker implementation for operation fixarsim to set
     */
    public void setFixarsimProgramInvoker(
            final FixarsimProgramInvoker programInvoker) {
        mFixarsimProgramInvoker = programInvoker;
    }
    
}
