
package com.legstar.test.cixs.lsfilead;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "lsfileadService", targetNamespace = "http://cixs.test.legstar.com/lsfilead", wsdlLocation = "http://localhost:8080/cixs-lsfilead/lsfilead?wsdl")
public class LsfileadService
    extends Service
{

    private final static URL LSFILEADSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cixs-lsfilead/lsfilead?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LSFILEADSERVICE_WSDL_LOCATION = url;
    }

    public LsfileadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LsfileadService() {
        super(LSFILEADSERVICE_WSDL_LOCATION, new QName("http://cixs.test.legstar.com/lsfilead", "lsfileadService"));
    }

    /**
     * 
     * @return
     *     returns LsfileadPort
     */
    @WebEndpoint(name = "LsfileadImplPort")
    public LsfileadPort getLsfileadImplPort() {
        return (LsfileadPort)super.getPort(new QName("http://cixs.test.legstar.com/lsfilead", "LsfileadImplPort"), LsfileadPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LsfileadPort
     */
    @WebEndpoint(name = "LsfileadImplPort")
    public LsfileadPort getLsfileadImplPort(WebServiceFeature... features) {
        return (LsfileadPort)super.getPort(new QName("http://cixs.test.legstar.com/lsfilead", "LsfileadImplPort"), LsfileadPort.class, features);
    }

}
