
package com.legstar.test.cixs.redmulti;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "redmultiPort", targetNamespace = "http://cixs.test.legstar.com/redmulti")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.coxb.redmulti.ObjectFactory.class,
    com.legstar.test.cixs.redmulti.ObjectFactory.class
})
public interface RedmultiPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.redmulti.RedmultiResponse
     * @throws RedmultiFault
     */
    @WebMethod
    @WebResult(name = "RedmultiResponse", targetNamespace = "http://cixs.test.legstar.com/redmulti", partName = "result")
    public RedmultiResponse redmulti(
        @WebParam(name = "RedmultiRequest", targetNamespace = "http://cixs.test.legstar.com/redmulti", partName = "parameters")
        RedmultiRequest parameters,
        @WebParam(name = "HostHeader", targetNamespace = "http://cixs.test.legstar.com/redmulti", header = true, partName = "HostHeader")
        RedmultiHostHeader hostHeader)
        throws RedmultiFault
    ;

}
