//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.17 at 09:08:57 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://coxb.test.legstar.com/coxb137")
package com.legstar.test.coxb.coxb137;
