/*******************************************************************************
 * LegStar legacy Web-enablement .
 * Copyright (C)  2007 LegSem
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301  USA
 * 
 *     
 *****************************************************************************/

package com.legstar.test.coxb.doublmix.bind;

import com.legstar.host.HostException;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.rt.CComplexBinding;

import com.legstar.coxb.rt.CDoubleBinding;

import com.legstar.test.coxb.doublmix.DfhcommareaType;
import com.legstar.test.coxb.doublmix.ObjectFactory;

/**
 * This class was generated by COXB version 1.0.
 * 2007-01-26T18:17:27.531+01:00
 * This class implements a bi-directional binding between a cobol structure and
 * a java object. Visitors can use this class to visit each element of the
 * structure in turn. No reflection or annotations are used which makes this
 * class suitable for heavy loads.
 */

public class DfhcommareaTypeBinding 
             extends CComplexBinding
             implements ICobolBinding {
  
    /** Name of java property to which this cobol element is bound. */
    private static final String JAVA_NAME = "DfhcommareaType";
  
    /** Type of java property to which this cobol element is bound. */
    private static final String JAVA_TYPE = "DfhcommareaType";
    
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble1234;
            
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble0;
            
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble1;
            
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble345006P5678;
            
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble798P20067Em16;
            
    /** Child property CDoubleBinding of simple type. */
    public CDoubleBinding cDouble3P40282347Ep38;
            
    /** Java object to which this cobol complex array element is bound. */
    private DfhcommareaType mJaxbObject;
  
    /** Java object factory for objects creation. */
    private ObjectFactory mObjectFactory;
  
    /**
     * No argument constructor.
     */
    public DfhcommareaTypeBinding() {
        this(null, null, null);
    }
  
    /**
     * Constructor for a child complex binding which be later bound to a JAXB
     * object.
     * @param parentObject the parent binding
     */
    public DfhcommareaTypeBinding(
        final CComplexBinding parentObject) {
        this(parentObject, null, null);
    }
  
    /**
     * Constructor for a root complex binding without an initial bound object.
     * @param objectFactory the java factory to use to create children instances
     */
    public DfhcommareaTypeBinding(
        final ObjectFactory objectFactory) {
        this(null, objectFactory, null);
    }

    /**
     * Constructor for a root complex binding from an existing java object.
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public DfhcommareaTypeBinding(
        final ObjectFactory objectFactory,
        final DfhcommareaType jaxbObject) {
        this(null, objectFactory, jaxbObject);
    }

    /**
     * Constructor for a child complex binding with immediate binding to a JAXB
     * object.
     * @param parentObject the parent binding
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public DfhcommareaTypeBinding(
        final CComplexBinding parentObject,
        final ObjectFactory objectFactory,
        final DfhcommareaType jaxbObject) {
        
        super(JAVA_NAME, JAVA_TYPE, parentObject);
        mJaxbObject = jaxbObject;
        mObjectFactory = objectFactory;
        initChildren();
    }
  
    /** Creates a binding property for each child. */
    public final void initChildren() {
    
        /* Create binding children instances */
        cDouble1234 = new CDoubleBinding("cDouble1234");
        cDouble1234.setCobolName("C-DOUBLE-1234");
        cDouble0 = new CDoubleBinding("cDouble0");
        cDouble0.setCobolName("C-DOUBLE-0");
        cDouble1 = new CDoubleBinding("cDouble1");
        cDouble1.setCobolName("C-DOUBLE-1");
        cDouble345006P5678 = new CDoubleBinding("cDouble345006P5678");
        cDouble345006P5678.setCobolName("C-DOUBLE-345006p5678");
        cDouble798P20067Em16 = new CDoubleBinding("cDouble798P20067Em16");
        cDouble798P20067Em16.setCobolName("C-DOUBLE-798p20067em16");
        cDouble3P40282347Ep38 = new CDoubleBinding("cDouble3P40282347Ep38");
        cDouble3P40282347Ep38.setCobolName("C-DOUBLE-3p40282347ep38");
        
        /* Add children to children list */
           
        getChildrenList().add(cDouble1234);
        getChildrenList().add(cDouble0);
        getChildrenList().add(cDouble1);
        getChildrenList().add(cDouble345006P5678);
        getChildrenList().add(cDouble798P20067Em16);
        getChildrenList().add(cDouble3P40282347Ep38);
    }
  
   
    /** {@inheritDoc} */
    public final void createBoundObject() throws HostException {
        setJaxbObject(mObjectFactory.createDfhcommareaType());
    }
       
    /** {@inheritDoc} */
    public final void prepareChildren() throws HostException {
    
    }
  
   
    /** {@inheritDoc} */
    public final void getValuesFromBoundObject() throws HostException {
        /* Set this binding properties from java object property values */
                     
        if (mJaxbObject.getCDouble1234() != 0d) {
            /* Set value from cDouble1234*/
            cDouble1234.setValue(mJaxbObject.getCDouble1234());
        }
                
        if (mJaxbObject.getCDouble0() != 0d) {
            /* Set value from cDouble0*/
            cDouble0.setValue(mJaxbObject.getCDouble0());
        }
                
        if (mJaxbObject.getCDouble1() != 0d) {
            /* Set value from cDouble1*/
            cDouble1.setValue(mJaxbObject.getCDouble1());
        }
                
        if (mJaxbObject.getCDouble345006P5678() != 0d) {
            /* Set value from cDouble345006P5678*/
            cDouble345006P5678.setValue(mJaxbObject.getCDouble345006P5678());
        }
                
        if (mJaxbObject.getCDouble798P20067Em16() != 0d) {
            /* Set value from cDouble798P20067Em16*/
            cDouble798P20067Em16.setValue(mJaxbObject.getCDouble798P20067Em16());
        }
                
        if (mJaxbObject.getCDouble3P40282347Ep38() != 0d) {
            /* Set value from cDouble3P40282347Ep38*/
            cDouble3P40282347Ep38.setValue(mJaxbObject.getCDouble3P40282347Ep38());
        }
    
    }
       
    /** {@inheritDoc} */
    public final void setBoundObjectValue(final int index) throws HostException {
        /* Set the JAXB object property value from binding object */
        switch (index) {
        case 0:
            setBoundObjectValueCDouble1234();
            break;
        case 1:
            setBoundObjectValueCDouble0();
            break;
        case 2:
            setBoundObjectValueCDouble1();
            break;
        case 3:
            setBoundObjectValueCDouble345006P5678();
            break;
        case 4:
            setBoundObjectValueCDouble798P20067Em16();
            break;
        case 5:
            setBoundObjectValueCDouble3P40282347Ep38();
            break;
        }
    }
            
    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble1234() throws HostException {
    
        if (cDouble1234.getValue() != null) {
            /* Set value of cDouble1234*/
            mJaxbObject.setCDouble1234(cDouble1234.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble0() throws HostException {
    
        if (cDouble0.getValue() != null) {
            /* Set value of cDouble0*/
            mJaxbObject.setCDouble0(cDouble0.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble1() throws HostException {
    
        if (cDouble1.getValue() != null) {
            /* Set value of cDouble1*/
            mJaxbObject.setCDouble1(cDouble1.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble345006P5678() throws HostException {
    
        if (cDouble345006P5678.getValue() != null) {
            /* Set value of cDouble345006P5678*/
            mJaxbObject.setCDouble345006P5678(cDouble345006P5678.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble798P20067Em16() throws HostException {
    
        if (cDouble798P20067Em16.getValue() != null) {
            /* Set value of cDouble798P20067Em16*/
            mJaxbObject.setCDouble798P20067Em16(cDouble798P20067Em16.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueCDouble3P40282347Ep38() throws HostException {
    
        if (cDouble3P40282347Ep38.getValue() != null) {
            /* Set value of cDouble3P40282347Ep38*/
            mJaxbObject.setCDouble3P40282347Ep38(cDouble3P40282347Ep38.getValue());
        }
        
    }

    /** {@inheritDoc} */
    public final Object getValue() throws HostException {
        return mJaxbObject;
    }

    /**
     * @return the java object to which this cobol complex element is bound
     */
    public final DfhcommareaType getJaxbObject() {
        return mJaxbObject;
    }

    /**
     * @param jaxbObject the java object to which this cobol complex element
     * is bound
     */
    public final void setJaxbObject(
        final DfhcommareaType jaxbObject) {
        mJaxbObject = jaxbObject;
    }

    /**
     * @return the java object factory for objects creation
     */
    public final ObjectFactory getObjectFactory() {
        return mObjectFactory;
    }

    /**
     * @param objectFactory the java object factory for objects creation to set
     */
    public final void setObjectFactory(final ObjectFactory objectFactory) {
        mObjectFactory = objectFactory;
    }

}
