package com.legstar.test.cixs.lsfileam;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.legstar.test.coxb.lsfileac.ReplyData;
import com.legstar.test.coxb.lsfileac.ReplyStatus;

/**
 * LegStar/Jaxws Operation Response Holder.
 * A container class for multi-elements Responses.
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */

@XmlRootElement(name = "LsfileamResponseHolder")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LsfileamResponseHolder",
         namespace = "http://cixs.test.legstar.com/lsfileam",
         propOrder = {
    "replyData",
    "replyStatus" })
public class LsfileamResponseHolder
    implements Serializable {

    /** Serial version ID. */
    private static final long serialVersionUID = 1L;

    /** Inner ReplyData JAXB-bound object. */
    @XmlElement(name = "ReplyData",
                namespace = "http://legstar.com/test/coxb/lsfileac",
                required = true)
    private ReplyData replyData;
    /** Inner ReplyStatus JAXB-bound object. */
    @XmlElement(name = "ReplyStatus",
                namespace = "http://legstar.com/test/coxb/lsfileac",
                required = true)
    private ReplyStatus replyStatus;

    /**
     * Get the inner ReplyData JAXB-bound object.
     * 
     * @return JAXB-bound object
     */
    public ReplyData getReplyData() {
        return replyData;
    }
    
    /**
     * Set the inner ReplyData JAXB-bound object.
     * 
     * @param value JAXB-bound object
     */
    public void setReplyData(
            final ReplyData value) {
        replyData = value;
    }
    /**
     * Get the inner ReplyStatus JAXB-bound object.
     * 
     * @return JAXB-bound object
     */
    public ReplyStatus getReplyStatus() {
        return replyStatus;
    }
    
    /**
     * Set the inner ReplyStatus JAXB-bound object.
     * 
     * @param value JAXB-bound object
     */
    public void setReplyStatus(
            final ReplyStatus value) {
        replyStatus = value;
    }
}
