package com.legstar.test.cixs.floatmix;
import javax.xml.ws.WebFault;

/**
 * LegStar/Jaxws Operation fault.
 * Fault element used as return message when an exception occurs.
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */
@WebFault(name = "FloatmixFaultInfo",
          targetNamespace = "http://cixs.test.legstar.com/floatmix")
public class FloatmixFault
    extends Exception {

    /** Default serialVersionUID.  */
    private static final long serialVersionUID = 1L;

    /** Java type that goes as soapenv:Fault detail element. */
    private FloatmixFaultInfo faultInfo;

    /**
     * Constructor for Web Fault.
     * @param fault error details
     * @param message error summary
     */
    public FloatmixFault(
        final String message,
        final FloatmixFaultInfo fault) {
      
        super(message);
        faultInfo = fault;
    }

    /**
     * Constructor for Web Fault with cause.
     * @param fault error details
     * @param message error summary
     * @param cause the cause
     */
    public FloatmixFault(
        final String message,
        final FloatmixFaultInfo fault,
        final Throwable cause) {
        
        super(message, cause);
        faultInfo = fault;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.floatmix.FloatmixFaultInfo
     */
    public FloatmixFaultInfo getFaultInfo() {
        return faultInfo;
    }

}

