//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.14 at 05:10:38 PM CEST 
//


package com.legstar.test.lsfileac;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolType;
import com.legstar.coxb.annotation.CobolElement;


/**
 * <p>Java class for WQueryDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WQueryDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WQueryName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WQueryAddress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WQueryPhone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WQueryDataType", propOrder = {
    "wQueryName",
    "wQueryAddress",
    "wQueryPhone"
})
public class WQueryDataType {

    @XmlElement(name = "WQueryName", required = true)
    @CobolElement(cobolName = "W-QUERY-NAME", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 20, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wQueryName;
    @XmlElement(name = "WQueryAddress", required = true)
    @CobolElement(cobolName = "W-QUERY-ADDRESS", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 20, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wQueryAddress;
    @XmlElement(name = "WQueryPhone", required = true)
    @CobolElement(cobolName = "W-QUERY-PHONE", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 8, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wQueryPhone;

    /**
     * Gets the value of the wQueryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWQueryName() {
        return wQueryName;
    }

    /**
     * Sets the value of the wQueryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWQueryName(String value) {
        this.wQueryName = value;
    }

    public boolean isSetWQueryName() {
        return (this.wQueryName!= null);
    }

    /**
     * Gets the value of the wQueryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWQueryAddress() {
        return wQueryAddress;
    }

    /**
     * Sets the value of the wQueryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWQueryAddress(String value) {
        this.wQueryAddress = value;
    }

    public boolean isSetWQueryAddress() {
        return (this.wQueryAddress!= null);
    }

    /**
     * Gets the value of the wQueryPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWQueryPhone() {
        return wQueryPhone;
    }

    /**
     * Sets the value of the wQueryPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWQueryPhone(String value) {
        this.wQueryPhone = value;
    }

    public boolean isSetWQueryPhone() {
        return (this.wQueryPhone!= null);
    }

}
