
package com.legstar.test.cixs.arraysdo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "arraysdoService", targetNamespace = "http://cixs.test.legstar.com/arraysdo", wsdlLocation = "http://localhost:8080/cixs-arraysdo/arraysdo?wsdl")
public class ArraysdoService
    extends Service
{

    private final static URL ARRAYSDOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.legstar.test.cixs.arraysdo.ArraysdoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.legstar.test.cixs.arraysdo.ArraysdoService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/cixs-arraysdo/arraysdo?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/cixs-arraysdo/arraysdo?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ARRAYSDOSERVICE_WSDL_LOCATION = url;
    }

    public ArraysdoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArraysdoService() {
        super(ARRAYSDOSERVICE_WSDL_LOCATION, new QName("http://cixs.test.legstar.com/arraysdo", "arraysdoService"));
    }

    /**
     * 
     * @return
     *     returns ArraysdoPort
     */
    @WebEndpoint(name = "arraysdoPort")
    public ArraysdoPort getArraysdoPort() {
        return super.getPort(new QName("http://cixs.test.legstar.com/arraysdo", "arraysdoPort"), ArraysdoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArraysdoPort
     */
    @WebEndpoint(name = "arraysdoPort")
    public ArraysdoPort getArraysdoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cixs.test.legstar.com/arraysdo", "arraysdoPort"), ArraysdoPort.class, features);
    }

}
