
package com.legstar.test.cixs.arraysdo;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Web service endpoint interface.
 * 
 * This class was generated by CIXS generator.
 * 2007-07-26T14:36:17+02:00
 */

@WebService(name = "arraysdoPort",
            targetNamespace = "http://cixs.test.legstar.com/arraysdo")
public interface Arraysdo {


    /**
     * Service operation arraysdo.
     * 
     * @param request a JAXB object mapping the request
     * @param hostHeader a JAXB object mapping header parameters
     * @return a JAXB object mapping the reply
     * @throws ArraysdoFault if method fails
     */
    @WebMethod
    @WebResult(name = "Response",
        targetNamespace = "http://cixs.test.legstar.com/arraysdo")
    @RequestWrapper(localName = "ArraysdoRequest",
        targetNamespace = "http://cixs.test.legstar.com/arraysdo",
        className = "com.legstar.test.cixs.arraysdo.ArraysdoRequest")
    @ResponseWrapper(localName = "ArraysdoResponse",
        targetNamespace = "http://cixs.test.legstar.com/arraysdo",
        className = "com.legstar.test.cixs.arraysdo.ArraysdoResponse")
    com.legstar.test.coxb.arraysdo.DfhcommareaType arraysdo(
        @WebParam(name = "Request",
               targetNamespace = "http://cixs.test.legstar.com/arraysdo")
        com.legstar.test.coxb.arraysdo.DfhcommareaType request,
        @WebParam(name = "HostHeader", header = true, partName = "HostHeader",
                targetNamespace = "http://cixs.test.legstar.com/arraysdo")
        ArraysdoHostHeader hostHeader)
        throws ArraysdoFault;

}

