
package com.legstar.test.cixs.lsfileae;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Web service endpoint interface.
 * 
 * This class was generated by CIXS generator.
 * 2007-04-06T12:06:19.078+02:00
 */

@WebService(name = "lsfileaePort",
            targetNamespace = "http://cixs.test.legstar.com/lsfileae")
public interface Lsfileae {


    /**
     * Service operation lsfileae.
     * 
     * @param request a JAXB object mapping the request
     * @param hostHeader a JAXB object mapping header parameters
     * @return a JAXB object mapping the reply
     * @throws LsfileaeFault if method fails
     */
    @WebMethod
    @WebResult(name = "Response",
               targetNamespace = "http://cixs.test.legstar.com/lsfileae")
    @RequestWrapper(localName = "LsfileaeRequest",
               targetNamespace = "http://cixs.test.legstar.com/lsfileae",
               className = "com.legstar.test.cixs.lsfileae.LsfileaeRequest")
    @ResponseWrapper(localName = "LsfileaeResponse",
               targetNamespace = "http://cixs.test.legstar.com/lsfileae",
               className = "com.legstar.test.cixs.lsfileae.LsfileaeResponse")
    com.legstar.test.coxb.lsfileae.
    DfhcommareaType lsfileae(
        @WebParam(name = "Request",
               targetNamespace = "http://cixs.test.legstar.com/lsfileae")
        com.legstar.test.coxb.lsfileae.
        DfhcommareaType request,
        @WebParam(name = "HostHeader", header = true, partName = "HostHeader",
                targetNamespace = "http://cixs.test.legstar.com/lsfileae")
        LsfileaeHostHeader hostHeader)
        throws LsfileaeFault;

}

