//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.11 at 02:03:49 PM CEST 
//


package com.legstar.test.coxb.lsfileac;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for WQueryLimitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WQueryLimitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WMaxItemsRead">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WMaxElapseTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WQueryLimitType", propOrder = {
    "wMaxItemsRead",
    "wMaxElapseTime"
})
public class WQueryLimitType {

    @XmlElement(name = "WMaxItemsRead")
    @CobolElement(cobolName = "W-MAX-ITEMS-READ", type = CobolType.PACKED_DECIMAL_ITEM, levelNumber = 5, byteLength = 5, isSigned = false, totalDigits = 8, picture = "9(8)", usage = "PACKED-DECIMAL", srceLine = 37)
    protected long wMaxItemsRead;
    @XmlElement(name = "WMaxElapseTime")
    @CobolElement(cobolName = "W-MAX-ELAPSE-TIME", type = CobolType.PACKED_DECIMAL_ITEM, levelNumber = 5, byteLength = 5, isSigned = false, totalDigits = 8, picture = "9(8)", usage = "PACKED-DECIMAL", srceLine = 38)
    protected long wMaxElapseTime;

    /**
     * Gets the value of the wMaxItemsRead property.
     * 
     */
    public long getWMaxItemsRead() {
        return wMaxItemsRead;
    }

    /**
     * Sets the value of the wMaxItemsRead property.
     * 
     */
    public void setWMaxItemsRead(long value) {
        this.wMaxItemsRead = value;
    }

    public boolean isSetWMaxItemsRead() {
        return true;
    }

    /**
     * Gets the value of the wMaxElapseTime property.
     * 
     */
    public long getWMaxElapseTime() {
        return wMaxElapseTime;
    }

    /**
     * Sets the value of the wMaxElapseTime property.
     * 
     */
    public void setWMaxElapseTime(long value) {
        this.wMaxElapseTime = value;
    }

    public boolean isSetWMaxElapseTime() {
        return true;
    }

}
