
package com.legstar.test.cixs.floatmix;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "floatmixPort", targetNamespace = "http://cixs.test.legstar.com/floatmix")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.coxb.floatmix.ObjectFactory.class,
    com.legstar.test.cixs.floatmix.ObjectFactory.class
})
public interface FloatmixPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.floatmix.FloatmixResponse
     * @throws FloatmixFault
     */
    @WebMethod(action = "urn:floatmix")
    @WebResult(name = "FloatmixResponse", targetNamespace = "http://cixs.test.legstar.com/floatmix", partName = "result")
    public FloatmixResponse floatmix(
        @WebParam(name = "FloatmixRequest", targetNamespace = "http://cixs.test.legstar.com/floatmix", partName = "parameters")
        FloatmixRequest parameters,
        @WebParam(name = "FloatmixHostHeader", targetNamespace = "http://cixs.test.legstar.com/floatmix", header = true, partName = "hostHeader")
        FloatmixHostHeader hostHeader)
        throws FloatmixFault
    ;

}
