package com.legstar.test.cixs.redmulti;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.legstar.test.coxb.redmulti.Dfhcommarea;
/**
 * LegStar/Jaxws Component interface.
 * Each method maps to a CICS program. 
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */
@WebService(name = "redmultiPort",
            targetNamespace = "http://cixs.test.legstar.com/redmulti")
public interface Redmulti {
  
    /**
     * LegStar operation redmulti.
     * 
     * @param request a JAXB object mapping the request
     * @param hostHeader an object mapping header parameters
     * @return a JAXB object mapping the reply
     * @throws RedmultiFault if method fails
     */
    @WebMethod(operationName = "redmulti", action = "urn:redmulti")
    @WebResult(name = "Dfhcommarea",
        targetNamespace = "http://legstar.com/test/coxb/redmulti")
    @RequestWrapper(localName = "RedmultiRequest",
        targetNamespace = "http://cixs.test.legstar.com/redmulti",
        className = "com.legstar.test.cixs.redmulti.RedmultiRequest")
    @ResponseWrapper(localName = "RedmultiResponse",
        targetNamespace = "http://cixs.test.legstar.com/redmulti",
        className = "com.legstar.test.cixs.redmulti.RedmultiResponse")
    Dfhcommarea redmulti(
        @WebParam(name = "Dfhcommarea",
               targetNamespace = "http://legstar.com/test/coxb/redmulti")
            Dfhcommarea request,
        @WebParam(name = "RedmultiHostHeader", header = true, partName = "hostHeader",
                targetNamespace = "http://cixs.test.legstar.com/redmulti")
            RedmultiHostHeader hostHeader)
        throws RedmultiFault;
        
}
