package com.legstar.test.cixs.lsfileac1;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.legstar.test.coxb.lsfileac.QueryData;
import com.legstar.test.coxb.lsfileac.ReplyData;
/**
 * LegStar/Jaxws Component interface.
 * Each method maps to a CICS program. 
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */
@WebService(name = "lsfileac1Port",
            targetNamespace = "http://cixs.test.legstar.com/lsfileac1")
public interface Lsfileac1 {
  
    /**
     * LegStar operation lsfileac.
     * 
     * @param request a JAXB object mapping the request
     * @param hostHeader an object mapping header parameters
     * @return a JAXB object mapping the reply
     * @throws LsfileacException if method fails
     */
    @WebMethod(operationName = "lsfileac", action = "urn:lsfileac")
    @WebResult(name = "ReplyData",
        targetNamespace = "http://legstar.com/test/coxb/lsfileac")
    @RequestWrapper(localName = "LsfileacRequest",
        targetNamespace = "http://cixs.test.legstar.com/lsfileac1",
        className = "com.legstar.test.cixs.lsfileac1.LsfileacRequest")
    @ResponseWrapper(localName = "LsfileacResponse",
        targetNamespace = "http://cixs.test.legstar.com/lsfileac1",
        className = "com.legstar.test.cixs.lsfileac1.LsfileacResponse")
    ReplyData lsfileac(
        @WebParam(name = "QueryData",
               targetNamespace = "http://legstar.com/test/coxb/lsfileac")
            QueryData request,
        @WebParam(name = "Lsfileac1HostHeader", header = true, partName = "hostHeader",
                targetNamespace = "http://cixs.test.legstar.com/lsfileac1")
            Lsfileac1HostHeader hostHeader)
        throws LsfileacException;
        
}
