
package com.legstar.test.cixs.doublmix;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DoublmixFaultInfo", targetNamespace = "http://cixs.test.legstar.com/doublmix")
public class DoublmixFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DoublmixFaultInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DoublmixFault(String message, DoublmixFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public DoublmixFault(String message, DoublmixFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.doublmix.DoublmixFaultInfo
     */
    public DoublmixFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
