
package com.legstar.test.cixs.lsfileax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lsfileaxPort", targetNamespace = "http://cixs.test.legstar.com/lsfileax")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.cixs.lsfileax.ObjectFactory.class,
    com.legstar.test.coxb.lsfileae.ObjectFactory.class,
    com.legstar.test.coxb.lsfileac.ObjectFactory.class
})
public interface LsfileaxPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.lsfileax.LsfileacResponse
     * @throws LsfileacFault
     */
    @WebMethod(action = "urn:lsfileac")
    @WebResult(name = "LsfileacResponse", targetNamespace = "http://cixs.test.legstar.com/lsfileax", partName = "result")
    public LsfileacResponse lsfileac(
        @WebParam(name = "LsfileacRequest", targetNamespace = "http://cixs.test.legstar.com/lsfileax", partName = "parameters")
        LsfileacRequest parameters,
        @WebParam(name = "LsfileaxHostHeader", targetNamespace = "http://cixs.test.legstar.com/lsfileax", header = true, partName = "hostHeader")
        LsfileaxHostHeader hostHeader)
        throws LsfileacFault
    ;

    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.lsfileax.LsfileaeResponse
     * @throws LsfileaeFault
     */
    @WebMethod(action = "urn:lsfileae")
    @WebResult(name = "LsfileaeResponse", targetNamespace = "http://cixs.test.legstar.com/lsfileax", partName = "result")
    public LsfileaeResponse lsfileae(
        @WebParam(name = "LsfileaeRequest", targetNamespace = "http://cixs.test.legstar.com/lsfileax", partName = "parameters")
        LsfileaeRequest parameters,
        @WebParam(name = "LsfileaxHostHeader", targetNamespace = "http://cixs.test.legstar.com/lsfileax", header = true, partName = "hostHeader")
        LsfileaxHostHeader hostHeader)
        throws LsfileaeFault
    ;

}
