/* This is a JNI wrapper for the Cobol to XSD DLL COB2XSD */
/* It is mainly a bridge converting parameter sets from JNI to straight C  */
#include <stdio.h>
#include <stdlib.h>
#include "COBDDPAS.h" /* Cobol dd parsing structures */
#include "XSDDDPRS.h" /* Xsd production structures */
#include "COB2XSDM.h" /* Cobol to XSD external methods */
#include "com_legstar_schemagen_COB2XSDJNIWrapper.h"   /*this header file was generated by javah */
#include "com_legstar_schemagen_UTILJNIWrapper.h" /* Utility method prototypes */

/* Global variables */
char* _sInFile;
char* _sRootName;
char* _sOutFile;
char _sMessage[256];
int _debugMode;
int  _rc;
jstring  _jsInFile, _jsRootName, _jsOutFile;
COBOL_COMPILER_OPTIONS _cobol_options; /* Cobol compiler options in effect */
XSD_PRODUCTION_OPTIONS _xsd_options; /* XML schema generation options */

/* converts from Java class representing cobol options to C struct */
int getCobolOptions(env, inVars)
    JNIEnv  *env;   /* JNI environment */
    jobject inVars; /* Incoming variables */
{
    jclass jcInVars;
    jobject joCobolOptions;
    jfieldID jfID;
    jthrowable exc;
    
    /* CobolOption is not mandatory. If it is not provided by the caller we get default values.
     * This means that we will recover from JNI exceptions trying to get those options. */
    joCobolOptions = NULL;
    jcInVars = (*env)->GetObjectClass(env, inVars); 
    jfID  = (*env)->GetFieldID(env, jcInVars, "cobolOptions", "Lcom/legstar/schemagen/COB2XSDJNIWrapper$CobolOptions;");
    exc = (*env)->ExceptionOccurred(env);
    if (!exc) {
        if (jfID != NULL) 
            joCobolOptions = (*env)->GetObjectField(env, inVars, jfID);
    }
    else {
         /* report exception and clear it */
        if (_debugMode)
             (*env)->ExceptionDescribe(env);
        (*env)->ExceptionClear(env);
        (*env)->DeleteLocalRef(env, exc);
    }
    if (joCobolOptions != NULL)
    {
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joCobolOptions, "includeDebugLines", &_cobol_options.include_debug_lines)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joCobolOptions, "truncBin", &_cobol_options.trunc_bin)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharFromString(env, joCobolOptions, "currencySign", &_cobol_options.currency_sign)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joCobolOptions, "decimalPointIsComma", &_cobol_options.decimal_point_is_comma)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joCobolOptions, "nsymbolDbcs", &_cobol_options.nsymbol_dbcs)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joCobolOptions, "quote", &_cobol_options.quote)) return JNI_ERR;
    }
    else
    {
        /* If not, get default values */
        getDefaultCobolOptions(&_cobol_options);
    }
    
    if (_debugMode) {
        printf("  Cobol options:\n");
        printf("    Debug lines         = %s\n", (_cobol_options.include_debug_lines)?"True":"False");
        printf("    Trunc bin           = %s\n", (_cobol_options.trunc_bin)?"True":"False");
        printf("    Currency sign       = %c\n", _cobol_options.currency_sign);
        printf("    Decimal point comma = %s\n", (_cobol_options.decimal_point_is_comma)?"True":"False");
        printf("    Nsymbol DBCS        = %s\n", (_cobol_options.nsymbol_dbcs)?"True":"False");
        printf("    Quote               = %s\n", (_cobol_options.quote)?"True":"False");
    }
    return 0;
}

/* converts from Java class representing XML schema generation options to C struct */
int getXsdOptions(env, inVars)
    JNIEnv  *env;   /* JNI environment */
    jobject inVars; /* Incoming variables */
{
    jclass jcInVars;
    jobject joXsdOptions;
    jfieldID jfID;
    jthrowable exc;
    
    /* XsdOption is not mandatory. If it is not provided by the caller we get default values.
     * This means that we will recover from JNI exceptions trying to get those options. */
    joXsdOptions = NULL;
    jcInVars = (*env)->GetObjectClass(env, inVars); 
    jfID  = (*env)->GetFieldID(env, jcInVars, "xsdOptions", "Lcom/legstar/schemagen/COB2XSDJNIWrapper$XsdOptions;");
    exc = (*env)->ExceptionOccurred(env);
    if (!exc) {
        if (jfID != NULL) 
            joXsdOptions = (*env)->GetObjectField(env, inVars, jfID);
    }
    else {
         /* report exception and clear it */
        if (_debugMode)
             (*env)->ExceptionDescribe(env);
        (*env)->ExceptionClear(env);
        (*env)->DeleteLocalRef(env, exc);
    }
    if (joXsdOptions != NULL)
    {
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joXsdOptions, "replaceMinus", &_xsd_options.replace_minus)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharFromString(env, joXsdOptions, "replaceMinusChar", &_xsd_options.replace_minus_char)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joXsdOptions, "removeMinus", &_xsd_options.remove_minus)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joXsdOptions, "uppercaseToLower", &_xsd_options.uppercase_to_lower)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joXsdOptions, "firstcharUpper", &_xsd_options.firstchar_upper)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "typeSuffix", _xsd_options.type_suffix, MAX_TYPE_SUFFIX_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsPrefix", _xsd_options.xs_prefix, MAX_PFX_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsNs", _xsd_options.xs_ns, MAX_NS_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsnsPrefix", _xsd_options.xsns_prefix, MAX_PFX_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsnsNs", _xsd_options.xsns_ns, MAX_NS_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xscbPrefix", _xsd_options.xscb_prefix, MAX_PFX_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xscbNs", _xsd_options.xscb_ns, MAX_NS_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsjaxbPrefix", _xsd_options.xsjaxb_prefix, MAX_PFX_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsjaxbNs", _xsd_options.xsjaxb_ns, MAX_NS_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsjaxbVersion", _xsd_options.xsjaxb_version, MAX_VERSION_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeCharsFromString(env, joXsdOptions, "xsjaxbPackage", _xsd_options.xsjaxb_package, MAX_PACKAGE_LEN)) return JNI_ERR;
        if (JNI_OK != JNU_SetNativeIntFromBoolean(env, joXsdOptions, "xsdHeaderFooter", &_xsd_options.xsd_header_footer)) return JNI_ERR;
    }
    else
    {
        /* If not, get default values */
        getDefaultXsdOptions(&_xsd_options);
    }
    
    if (_debugMode) {
        printf("  Xsd options:\n");
        printf("    Replace minus sign  = %s\n", (_xsd_options.replace_minus)?"True":"False");
        printf("    Replace minus char  = %c\n", _xsd_options.replace_minus_char);
        printf("    Remove minus sign   = %s\n", (_xsd_options.remove_minus)?"True":"False");
        printf("    Uppercase to lower  = %s\n", (_xsd_options.uppercase_to_lower)?"True":"False");
        printf("    First char uppercase= %s\n", (_xsd_options.firstchar_upper)?"True":"False");
        printf("    Suffix for types    = %s\n", _xsd_options.type_suffix);
        printf("    Xsd namespace prefix= %s\n", _xsd_options.xs_prefix);
        printf("    Xsd namespace       = %s\n", _xsd_options.xs_ns);
        printf("    Target namespace pfx= %s\n", _xsd_options.xsns_prefix);
        printf("    Target namespace    = %s\n", _xsd_options.xsns_ns);
        printf("    Cobol Namespace pfx = %s\n", _xsd_options.xscb_prefix);
        printf("    Cobol Namespace     = %s\n", _xsd_options.xscb_ns);
        printf("    JAXB Namespace pfx  = %s\n", _xsd_options.xsjaxb_prefix);
        printf("    JAXB Namespace      = %s\n", _xsd_options.xsjaxb_ns);
        printf("    JAXB version        = %s\n", _xsd_options.xsjaxb_version);
        printf("    Target class package= %s\n", _xsd_options.xsjaxb_package);
        printf("    XSD header/footer   = %s\n", (_xsd_options.xsd_header_footer)?"True":"False");
    }
    return 0;
}

/* Extract data from the JNI wrappers and set standard C variables equivalent*/
int prolog (env, obj, inVars)
    JNIEnv  *env;  /* JNI environment */
    jobject obj;   /* Object of the JNI command */
    jobject inVars; /* Incoming variables */
{
    _sMessage[0] = '\0';
    
    /* Get the java input object field values */
    if (JNI_OK != JNU_SetNativeIntFromBoolean(env, inVars, "debugMode", &_debugMode)) return JNI_ERR;
    if (JNI_OK != JNU_GetNativeCharsFromString(env, inVars, "inFile", &_sInFile)) return JNI_ERR;
    if (JNI_OK != JNU_GetNativeCharsFromString(env, inVars, "inRootName", &_sRootName)) return JNI_ERR;
    if (JNI_OK != JNU_GetNativeCharsFromString(env, inVars, "outFile", &_sOutFile)) return JNI_ERR;
     
    if (_debugMode) {
        printf("legstar_schemagen_COB2XSDJNIWrapper started with parameters:\n");
        printf("  Cobol source file name= %s\n",_sInFile);
        printf("  XSD root element name = %s\n",_sRootName);
        printf("  Output XSD file name  = %s\n",_sOutFile);
    }
    
    /* get the cobol options from input var */
    _rc = getCobolOptions(env, inVars);
    if (_rc != JNI_OK) return _rc;
    
    /* get the XML schema generation options from input var */
    _rc = getXsdOptions(env, inVars);
    if (_rc != JNI_OK) return _rc;
    
    return _rc;
}

/* Create the output JNI wrappers from standard C variables equivalent*/
int epilog (env, obj,  outVars)
    JNIEnv  *env;  /* JNI environment */
    jobject obj;   /* Object of the JNI command */
    jobject outVars; /* Variables returned */
{
     jthrowable exc;
     
    /* Must release memory allocated by JNU_GetStringNativeChars */
    free(_sInFile);
    free(_sRootName);
    free(_sOutFile);
    
    /* check if we have a cached exception pending */
     exc = (*env)->ExceptionOccurred(env);
     if (!exc) {
        /* No exceptions, create the output variables  */
        JNU_SetStringFromNativeChars(env, outVars, "message", _sMessage);
        if (_debugMode == 1) {
            printf("legstar_schemagen_COB2XSDJNIWrapper ended with values:\n");
            printf("  Message returned from COB2XSD=%s\n",_sMessage);
        }
     } else {
         /* We let the exception flow back to Java*/
         (*env)->DeleteLocalRef(env, exc);
         return JNI_ERR;
     }

    return JNI_OK;
}

JNIEXPORT jint JNICALL Java_com_legstar_schemagen_COB2XSDJNIWrapper_cob2xsd
  (JNIEnv  *env, jobject obj, jobject inVars, jobject outVars)
{
	/* Get all the input variables */
	_rc = prolog(env, obj, inVars); 
	
	/* Convert cobol source to XML schema */
	if (_rc == JNI_OK)
		_rc = Cobol2XMLSchema(
	           _debugMode,          /* 1= Debug traces in stdout         */
	           _sInFile,            /* Cobol source to parse             */
	           _sRootName,          /* XSD root element name             */
	           _sOutFile,           /* resulting XML schema              */
	           &_cobol_options,     /* cobol options in effect           */
	           &_xsd_options,       /* xml schema generation options     */
	           _sMessage);          /* Error message if any              */

	/* Set output variables  */
	epilog(env, obj, outVars); 
	return _rc;
}


