
package com.legstar.test.cixs.binnatsi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "binnatsiPort", targetNamespace = "http://cixs.test.legstar.com/binnatsi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.coxb.binnatsi.ObjectFactory.class,
    com.legstar.test.cixs.binnatsi.ObjectFactory.class
})
public interface BinnatsiPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.binnatsi.BinnatsiResponse
     * @throws BinnatsiFault
     */
    @WebMethod
    @WebResult(name = "BinnatsiResponse", targetNamespace = "http://cixs.test.legstar.com/binnatsi", partName = "result")
    public BinnatsiResponse binnatsi(
        @WebParam(name = "BinnatsiRequest", targetNamespace = "http://cixs.test.legstar.com/binnatsi", partName = "parameters")
        BinnatsiRequest parameters,
        @WebParam(name = "HostHeader", targetNamespace = "http://cixs.test.legstar.com/binnatsi", header = true, partName = "HostHeader")
        BinnatsiHostHeader hostHeader)
        throws BinnatsiFault
    ;

}
