
package com.legstar.test.cixs.doublmix;
import javax.xml.ws.WebFault;

/**
 * Fault element used as return message when an exception occurs.
 * 
 * This class was generated by CIXS generator.
 * 2007-07-09T13:00:54.671+02:00
 */

@WebFault(name = "DoublmixFaultInfo",
          targetNamespace = "http://cixs.test.legstar.com/doublmix")
public class DoublmixFault
    extends Exception {

    /** Default serialVersionUID.  */
	private static final long serialVersionUID = 1L;
	
    /** Java type that goes as soapenv:Fault detail element. */
    private DoublmixFaultInfo faultInfo;

    /**
     * Constructor for Web Fault.
     * @param fault error details
     * @param message error summary
     */
    public DoublmixFault(
    	final String message,
    	final DoublmixFaultInfo fault) {
    	
        super(message);
        this.faultInfo = fault;
    }

    /**
     * Constructor for Web Fault with cause.
     * @param fault error details
     * @param message error summary
     * @param cause the cause
     */
    public DoublmixFault(
        final String message,
        final DoublmixFaultInfo fault,
        final Throwable cause) {
        
        super(message, cause);
        this.faultInfo = fault;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.doublmix.DoublmixFaultInfo
     */
    public final DoublmixFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
