package com.legstar.test.cixs.lsfileam;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * LegStar/Jaxws Operation Response Wrapper.
 * A wrapper class for the Response.
 * 
 * This class was generated by LegStar Mainframe Web Service adapter generator.
 */

@XmlRootElement(name = "LsfileamResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LsfileamResponse",
         namespace = "http://cixs.test.legstar.com/lsfileam",
         propOrder = {
    "response"
})
public class LsfileamResponse {
    
    /** Inner JAXB-bound object. */
    @XmlElement(name = "LsfileamResponseHolder",
                namespace = "http://cixs.test.legstar.com/lsfileam",
                required = true)
    private LsfileamResponseHolder response;

    /**
    * Get the inner JAXB-bound object.
    * 
    * @return JAXB-bound object
    */
    public LsfileamResponseHolder getResponse() {
        return response;
    }

  /**
   * Set the inner JAXB-bound object.
   * 
   * @param value JAXB-bound object
   */
    public void setResponse(
            final LsfileamResponseHolder value) {
        response = value;
    }

}
