
package com.legstar.test.cixs.osarrays;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "OsarraysFaultInfo", targetNamespace = "http://cixs.test.legstar.com/osarrays")
public class OsarraysFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OsarraysFaultInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OsarraysFault(String message, OsarraysFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public OsarraysFault(String message, OsarraysFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.osarrays.OsarraysFaultInfo
     */
    public OsarraysFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
