//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.17 at 10:43:33 AM CEST 
//


package com.legstar.test.coxb.redinout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for CParainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CParainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CSomeInput">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CParainType", propOrder = {
    "cSomeInput"
})
public class CParainType {

    @XmlElement(name = "CSomeInput", required = true)
    @CobolElement(cobolName = "C-SOME-INPUT", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 10, byteLength = 15, picture = "X(15)", usage = "DISPLAY", srceLine = 24)
    protected String cSomeInput;

    /**
     * Gets the value of the cSomeInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSomeInput() {
        return cSomeInput;
    }

    /**
     * Sets the value of the cSomeInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSomeInput(String value) {
        this.cSomeInput = value;
    }

    public boolean isSetCSomeInput() {
        return (this.cSomeInput!= null);
    }

}
