/*******************************************************************************
 *  LegStar legacy Web-enablement .
 *  Copyright (C) 2007 LegSem
 *  
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *   
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 *  02110-1301  USA
 *  
 *******************************************************************************/

package com.legstar.test.coxb.lsfileal.bind;

import com.legstar.host.HostException;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.rt.CComplexBinding;

import com.legstar.coxb.rt.CBinaryBinding;
import com.legstar.coxb.rt.CStringBinding;
import java.math.BigDecimal;

import com.legstar.test.coxb.lsfileal.ReplyErrorHeaderType;
import com.legstar.test.coxb.lsfileal.ObjectFactory;

/**
 * This class was generated by COXB version 1.0.
 * 2007-01-26T18:17:52.671+01:00
 * This class implements a bi-directional binding between a cobol structure and
 * a java object. Visitors can use this class to visit each element of the
 * structure in turn. No reflection or annotations are used which makes this
 * class suitable for heavy loads.
 */

public class ReplyErrorHeaderTypeBinding 
             extends CComplexBinding
             implements ICobolBinding {
  
    /** Name of java property to which this cobol element is bound. */
    private static final String JAVA_NAME = "replyErrorHeader";
  
    /** Type of java property to which this cobol element is bound. */
    private static final String JAVA_TYPE = "ReplyErrorHeaderType";
    
    /** Child property CBinaryBinding of simple type. */
    public CBinaryBinding replyResp;
            
    /** Child property CBinaryBinding of simple type. */
    public CBinaryBinding replyResp2;
            
    /** Child property CStringBinding of simple type. */
    public CStringBinding replyMessage;
            
    /** Java object to which this cobol complex array element is bound. */
    private ReplyErrorHeaderType mJaxbObject;
  
    /** Java object factory for objects creation. */
    private ObjectFactory mObjectFactory;
  
    /**
     * No argument constructor.
     */
    public ReplyErrorHeaderTypeBinding() {
        this(null, null, null);
    }
  
    /**
     * Constructor for a child complex binding which be later bound to a JAXB
     * object.
     * @param parentObject the parent binding
     */
    public ReplyErrorHeaderTypeBinding(
        final CComplexBinding parentObject) {
        this(parentObject, null, null);
    }
  
    /**
     * Constructor for a root complex binding without an initial bound object.
     * @param objectFactory the java factory to use to create children instances
     */
    public ReplyErrorHeaderTypeBinding(
        final ObjectFactory objectFactory) {
        this(null, objectFactory, null);
    }

    /**
     * Constructor for a root complex binding from an existing java object.
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public ReplyErrorHeaderTypeBinding(
        final ObjectFactory objectFactory,
        final ReplyErrorHeaderType jaxbObject) {
        this(null, objectFactory, jaxbObject);
    }

    /**
     * Constructor for a child complex binding with immediate binding to a JAXB
     * object.
     * @param parentObject the parent binding
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public ReplyErrorHeaderTypeBinding(
        final CComplexBinding parentObject,
        final ObjectFactory objectFactory,
        final ReplyErrorHeaderType jaxbObject) {
        
        super(JAVA_NAME, JAVA_TYPE, parentObject);
        mJaxbObject = jaxbObject;
        mObjectFactory = objectFactory;
        initChildren();
    }
  
    /** Creates a binding property for each child. */
    public final void initChildren() {
    
        /* Create binding children instances */
        replyResp = new CBinaryBinding("replyResp", 4, 8, 0, true);
        replyResp.setCobolName("REPLY-RESP");
        replyResp2 = new CBinaryBinding("replyResp2", 4, 8, 0, true);
        replyResp2.setCobolName("REPLY-RESP2");
        replyMessage = new CStringBinding("replyMessage", 128, false);
        replyMessage.setCobolName("REPLY-MESSAGE");
        
        /* Add children to children list */
           
        getChildrenList().add(replyResp);
        getChildrenList().add(replyResp2);
        getChildrenList().add(replyMessage);
    }
  
   
    /** {@inheritDoc} */
    public final void createBoundObject() throws HostException {
        setJaxbObject(mObjectFactory.createReplyErrorHeaderType());
    }
       
    /** {@inheritDoc} */
    public final void prepareChildren() throws HostException {
    
    }
  
   
    /** {@inheritDoc} */
    public final void getValuesFromBoundObject() throws HostException {
        /* Set this binding properties from java object property values */
                     
        if (mJaxbObject.getReplyResp() != 0) {
            /* Set value from replyResp*/
            replyResp.setValue(new BigDecimal(mJaxbObject.getReplyResp()));
        
        }
                
        if (mJaxbObject.getReplyResp2() != 0) {
            /* Set value from replyResp2*/
            replyResp2.setValue(new BigDecimal(mJaxbObject.getReplyResp2()));
        
        }
                
        if (mJaxbObject.getReplyMessage() != null) {
            /* Set value from replyMessage*/
            replyMessage.setValue(mJaxbObject.getReplyMessage());
        }
    
    }
       
    /** {@inheritDoc} */
    public final void setBoundObjectValue(final int index) throws HostException {
        /* Set the JAXB object property value from binding object */
        switch (index) {
        case 0:
            setBoundObjectValueReplyResp();
            break;
        case 1:
            setBoundObjectValueReplyResp2();
            break;
        case 2:
            setBoundObjectValueReplyMessage();
            break;
        }
    }
            
    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyResp() throws HostException {
    
        if (replyResp.getValue() != null) {
            
            /* Set value of replyResp*/
            mJaxbObject.setReplyResp(replyResp.getValue().intValueExact());
                
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyResp2() throws HostException {
    
        if (replyResp2.getValue() != null) {
            
            /* Set value of replyResp2*/
            mJaxbObject.setReplyResp2(replyResp2.getValue().intValueExact());
                
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyMessage() throws HostException {
    
        if (replyMessage.getValue() != null) {
            /* Set value of replyMessage*/
            mJaxbObject.setReplyMessage(replyMessage.getValue());
        }
        
    }

    /** {@inheritDoc} */
    public final Object getValue() throws HostException {
        return mJaxbObject;
    }

    /**
     * @return the java object to which this cobol complex element is bound
     */
    public final ReplyErrorHeaderType getJaxbObject() {
        return mJaxbObject;
    }

    /**
     * @param jaxbObject the java object to which this cobol complex element
     * is bound
     */
    public final void setJaxbObject(
        final ReplyErrorHeaderType jaxbObject) {
        mJaxbObject = jaxbObject;
    }

    /**
     * @return the java object factory for objects creation
     */
    public final ObjectFactory getObjectFactory() {
        return mObjectFactory;
    }

    /**
     * @param objectFactory the java object factory for objects creation to set
     */
    public final void setObjectFactory(final ObjectFactory objectFactory) {
        mObjectFactory = objectFactory;
    }

}
