
package com.legstar.test.lsfileac.bind;

import com.legstar.host.HostException;
import com.legstar.test.lsfileac.ObjectFactory;
import com.legstar.test.lsfileac.ReplyItemType;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.rt.CComplexBinding;

import com.legstar.coxb.rt.CStringBinding;
import com.legstar.coxb.rt.CZonedDecimalBinding;
import java.math.BigDecimal;


/**
 * This class was generated by COXB version 1.0.
 * 2007-05-14T17:10:43.218+02:00
 * This class implements a bi-directional binding between a cobol structure and
 * a java object. Visitors can use this class to visit each element of the
 * structure in turn. No reflection or annotations are used which makes this
 * class suitable for heavy loads.
 */

public class ReplyItemTypeBinding 
             extends CComplexBinding
             implements ICobolBinding {
  
    /** Name of java property to which this cobol element is bound. */
    private static final String JAVA_NAME = "replyItem";
  
    /** Type of java property to which this cobol element is bound. */
    private static final String JAVA_TYPE = "ReplyItemType";
    
    /** Child property CZonedDecimalBinding of simple type. */
    public CZonedDecimalBinding replyNumber;
            
    /** Child property ReplyPersonalTypeBinding of complex type. */
    public ReplyPersonalTypeBinding replyPersonal;
            
    /** Child property CStringBinding of simple type. */
    public CStringBinding replyDate;
            
    /** Child property CStringBinding of simple type. */
    public CStringBinding replyAmount;
            
    /** Child property CStringBinding of simple type. */
    public CStringBinding replyComment;
            
    /** Java object to which this cobol complex array element is bound. */
    private ReplyItemType mJaxbObject;
  
    /** Java object factory for objects creation. */
    private ObjectFactory mObjectFactory;
  
    /**
     * No argument constructor.
     */
    public ReplyItemTypeBinding() {
        this(null, null, null);
    }
  
    /**
     * Constructor for a child complex binding which be later bound to a JAXB
     * object.
     * @param parentObject the parent binding
     */
    public ReplyItemTypeBinding(
        final CComplexBinding parentObject) {
        this(parentObject, null, null);
    }
  
    /**
     * Constructor for a root complex binding without an initial bound object.
     * @param objectFactory the java factory to use to create children instances
     */
    public ReplyItemTypeBinding(
        final ObjectFactory objectFactory) {
        this(null, objectFactory, null);
    }

    /**
     * Constructor for a root complex binding from an existing java object.
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public ReplyItemTypeBinding(
        final ObjectFactory objectFactory,
        final ReplyItemType jaxbObject) {
        this(null, objectFactory, jaxbObject);
    }

    /**
     * Constructor for a child complex binding with immediate binding to a JAXB
     * object.
     * @param parentObject the parent binding
     * @param objectFactory the java factory to use to create children instances
     * @param jaxbObject the java object to which this element is bound
     */
    public ReplyItemTypeBinding(
        final CComplexBinding parentObject,
        final ObjectFactory objectFactory,
        final ReplyItemType jaxbObject) {
        
        super(JAVA_NAME, JAVA_TYPE, parentObject);
        mJaxbObject = jaxbObject;
        mObjectFactory = objectFactory;
        initChildren();
    }
  
    /** Creates a binding property for each child. */
    public final void initChildren() {
    
        /* Create binding children instances */
        replyNumber = new CZonedDecimalBinding("replyNumber", 6, 6, 0, false, false, false);
        replyNumber.setCobolName("REPLY-NUMBER");
        replyPersonal = new ReplyPersonalTypeBinding(this);
        replyDate = new CStringBinding("replyDate", 8, false);
        replyDate.setCobolName("REPLY-DATE");
        replyAmount = new CStringBinding("replyAmount", 8, false);
        replyAmount.setCobolName("REPLY-AMOUNT");
        replyComment = new CStringBinding("replyComment", 9, false);
        replyComment.setCobolName("REPLY-COMMENT");
        
        /* Add children to children list */
           
        getChildrenList().add(replyNumber);
        getChildrenList().add(replyPersonal);
        getChildrenList().add(replyDate);
        getChildrenList().add(replyAmount);
        getChildrenList().add(replyComment);
    }
  
   
    /** {@inheritDoc} */
    public final void createBoundObject() throws HostException {
        setJaxbObject(mObjectFactory.createReplyItemType());
    }
       
    /** {@inheritDoc} */
    public final void prepareChildren() throws HostException {
    
        /* Pass on the JAXB factory to child replyPersonal  */
        replyPersonal.setObjectFactory(mObjectFactory);

    }
  
   
    /** {@inheritDoc} */
    public final void getValuesFromBoundObject() throws HostException {
        /* Set this binding properties from java object property values */
                     
        if (mJaxbObject.getReplyNumber() != 0L) {
            /* Set value from replyNumber*/
            replyNumber.setValue(new BigDecimal(mJaxbObject.getReplyNumber()));
        
        }
                
        if (mJaxbObject.getReplyPersonal() != null) {
            /* Set value from replyPersonal*/
            replyPersonal.setJaxbObject(mJaxbObject.getReplyPersonal());
            
        } else {
            replyPersonal.setJaxbObject(mObjectFactory.createReplyPersonalType());
        }
                            
        if (mJaxbObject.getReplyDate() != null) {
            /* Set value from replyDate*/
            replyDate.setValue(mJaxbObject.getReplyDate());
        }
                
        if (mJaxbObject.getReplyAmount() != null) {
            /* Set value from replyAmount*/
            replyAmount.setValue(mJaxbObject.getReplyAmount());
        }
                
        if (mJaxbObject.getReplyComment() != null) {
            /* Set value from replyComment*/
            replyComment.setValue(mJaxbObject.getReplyComment());
        }
    
    }
       
    /** {@inheritDoc} */
    public final void setBoundObjectValue(final int index) throws HostException {
        /* Set the JAXB object property value from binding object */
        switch (index) {
        case 0:
            setBoundObjectValueReplyNumber();
            break;
        case 1:
            setBoundObjectValueReplyPersonal();
            break;
        case 2:
            setBoundObjectValueReplyDate();
            break;
        case 3:
            setBoundObjectValueReplyAmount();
            break;
        case 4:
            setBoundObjectValueReplyComment();
            break;
        }
    }
            
    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyNumber() throws HostException {
    
        if (replyNumber.getValue() != null) {
            
            /* Set value of replyNumber*/
            mJaxbObject.setReplyNumber(replyNumber.getValue().longValueExact());
                
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyPersonal() throws HostException {
    
        /* Set value of complex child replyPersonal*/
        mJaxbObject.setReplyPersonal(replyPersonal.getJaxbObject());
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyDate() throws HostException {
    
        if (replyDate.getValue() != null) {
            /* Set value of replyDate*/
            mJaxbObject.setReplyDate(replyDate.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyAmount() throws HostException {
    
        if (replyAmount.getValue() != null) {
            /* Set value of replyAmount*/
            mJaxbObject.setReplyAmount(replyAmount.getValue());
        }
        
    }

    /** Set corresponding JAXB object property value. */
    private final void setBoundObjectValueReplyComment() throws HostException {
    
        if (replyComment.getValue() != null) {
            /* Set value of replyComment*/
            mJaxbObject.setReplyComment(replyComment.getValue());
        }
        
    }

    /** {@inheritDoc} */
    public final Object getValue() throws HostException {
        return mJaxbObject;
    }

    /**
     * @return the java object to which this cobol complex element is bound
     */
    public final ReplyItemType getJaxbObject() {
        return mJaxbObject;
    }

    /**
     * @param jaxbObject the java object to which this cobol complex element
     * is bound
     */
    public final void setJaxbObject(
        final ReplyItemType jaxbObject) {
        mJaxbObject = jaxbObject;
    }

    /**
     * @return the java object factory for objects creation
     */
    public final ObjectFactory getObjectFactory() {
        return mObjectFactory;
    }

    /**
     * @param objectFactory the java object factory for objects creation to set
     */
    public final void setObjectFactory(final ObjectFactory objectFactory) {
        mObjectFactory = objectFactory;
    }

}
