//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.13 at 09:00:27 AM CEST 
//


package com.legstar.test.coxb.arrayssm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for TableComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ElementComplex">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableComplexType", propOrder = {
    "elementComplex"
})
public class TableComplexType {

    @XmlElement(name = "ElementComplex", required = true)
    @CobolElement(cobolName = "ELEMENT-COMPLEX", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 10, byteLength = 5, picture = "X(5)", usage = "DISPLAY", srceLine = 34)
    protected String elementComplex;

    /**
     * Gets the value of the elementComplex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementComplex() {
        return elementComplex;
    }

    /**
     * Sets the value of the elementComplex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementComplex(String value) {
        this.elementComplex = value;
    }

    public boolean isSetElementComplex() {
        return (this.elementComplex!= null);
    }

}
