//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.11 at 01:37:31 PM CEST 
//


package com.legstar.test.coxb.arrayssm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolElement;
import com.legstar.coxb.CobolType;


/**
 * <p>Java class for WsTcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WsTcType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Filler24">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WsTcA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WsTcType", propOrder = {
    "filler24",
    "wsTcA"
})
public class WsTcType {

    @XmlElement(name = "Filler24", required = true)
    @CobolElement(cobolName = "FILLER-24", type = CobolType.ALPHANUMERIC_ITEM, levelNumber = 5, byteLength = 4, picture = "X(4)", usage = "DISPLAY", srceLine = 24)
    protected String filler24;
    @XmlElement(name = "WsTcA")
    @CobolElement(cobolName = "WS-TC-A", type = CobolType.ZONED_DECIMAL_ITEM, levelNumber = 5, byteLength = 1, isSigned = false, totalDigits = 1, picture = "9(1)", usage = "DISPLAY", srceLine = 25)
    protected int wsTcA;

    /**
     * Gets the value of the filler24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiller24() {
        return filler24;
    }

    /**
     * Sets the value of the filler24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiller24(String value) {
        this.filler24 = value;
    }

    public boolean isSetFiller24() {
        return (this.filler24 != null);
    }

    /**
     * Gets the value of the wsTcA property.
     * 
     */
    public int getWsTcA() {
        return wsTcA;
    }

    /**
     * Sets the value of the wsTcA property.
     * 
     */
    public void setWsTcA(int value) {
        this.wsTcA = value;
    }

    public boolean isSetWsTcA() {
        return true;
    }

}
