/*******************************************************************************
 *  LegStar legacy Web-enablement .
 *  Copyright (C) 2007 LegSem
 *  
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *  
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *   
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 *  02110-1301  USA
 *  
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.26 at 06:16:49 PM CET 
//


package com.legstar.test.coxb.dplarcht;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.legstar.coxb.CobolType;
import com.legstar.coxb.annotation.CobolElement;


/**
 * <p>Java class for WsFileDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WsFileDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WsFileStart">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WsFileName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WsFileDsname">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="44"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WsFileEnablestatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WsFileDescriptionType", propOrder = {
    "wsFileStart",
    "wsFileName",
    "wsFileDsname",
    "wsFileEnablestatus"
})
public class WsFileDescriptionType {

    @XmlElement(name = "WsFileStart", required = true)
    @CobolElement(cobolName = "WS-FILE-START", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 8, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wsFileStart;
    @XmlElement(name = "WsFileName", required = true)
    @CobolElement(cobolName = "WS-FILE-NAME", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 8, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wsFileName;
    @XmlElement(name = "WsFileDsname", required = true)
    @CobolElement(cobolName = "WS-FILE-DSNAME", type = CobolType.ALPHANUMERIC_ITEM, byteLength = 44, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false)
    protected String wsFileDsname;
    @XmlElement(name = "WsFileEnablestatus")
    @CobolElement(cobolName = "WS-FILE-ENABLESTATUS", type = CobolType.BINARY_ITEM, byteLength = 4, isJustifiedRight = false, isSigned = false, isSignLeading = false, isSignSeparate = false, totalDigits = 8)
    protected long wsFileEnablestatus;

    /**
     * Gets the value of the wsFileStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsFileStart() {
        return wsFileStart;
    }

    /**
     * Sets the value of the wsFileStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsFileStart(String value) {
        this.wsFileStart = value;
    }

    public boolean isSetWsFileStart() {
        return (this.wsFileStart!= null);
    }

    /**
     * Gets the value of the wsFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsFileName() {
        return wsFileName;
    }

    /**
     * Sets the value of the wsFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsFileName(String value) {
        this.wsFileName = value;
    }

    public boolean isSetWsFileName() {
        return (this.wsFileName!= null);
    }

    /**
     * Gets the value of the wsFileDsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsFileDsname() {
        return wsFileDsname;
    }

    /**
     * Sets the value of the wsFileDsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsFileDsname(String value) {
        this.wsFileDsname = value;
    }

    public boolean isSetWsFileDsname() {
        return (this.wsFileDsname!= null);
    }

    /**
     * Gets the value of the wsFileEnablestatus property.
     * 
     */
    public long getWsFileEnablestatus() {
        return wsFileEnablestatus;
    }

    /**
     * Sets the value of the wsFileEnablestatus property.
     * 
     */
    public void setWsFileEnablestatus(long value) {
        this.wsFileEnablestatus = value;
    }

    public boolean isSetWsFileEnablestatus() {
        return true;
    }

}
