
package com.legstar.test.cixs.dplarcht;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dplarchtPort", targetNamespace = "http://cixs.test.legstar.com/dplarcht")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.cixs.dplarcht.ObjectFactory.class,
    com.legstar.test.coxb.dplarcht.ObjectFactory.class
})
public interface DplarchtPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.dplarcht.DplarchtResponse
     * @throws DplarchtFault
     */
    @WebMethod
    @WebResult(name = "DplarchtResponse", targetNamespace = "http://cixs.test.legstar.com/dplarcht", partName = "result")
    public DplarchtResponse dplarcht(
        @WebParam(name = "DplarchtRequest", targetNamespace = "http://cixs.test.legstar.com/dplarcht", partName = "parameters")
        DplarchtRequest parameters,
        @WebParam(name = "HostHeader", targetNamespace = "http://cixs.test.legstar.com/dplarcht", header = true, partName = "HostHeader")
        DplarchtHostHeader hostHeader)
        throws DplarchtFault
    ;

}
