
package com.legstar.test.cixs.binnatsi;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Web service endpoint interface.
 * 
 * This class was generated by CIXS generator.
 * 2007-07-09T13:00:46.218+02:00
 */

@WebService(name = "binnatsiPort",
            targetNamespace = "http://cixs.test.legstar.com/binnatsi")
public interface Binnatsi {


    /**
     * Service operation binnatsi.
     * 
     * @param request a JAXB object mapping the request
     * @param hostHeader a JAXB object mapping header parameters
     * @return a JAXB object mapping the reply
     * @throws BinnatsiFault if method fails
     */
    @WebMethod
    @WebResult(name = "Response",
        targetNamespace = "http://cixs.test.legstar.com/binnatsi")
    @RequestWrapper(localName = "BinnatsiRequest",
        targetNamespace = "http://cixs.test.legstar.com/binnatsi",
        className = "com.legstar.test.cixs.binnatsi.BinnatsiRequest")
    @ResponseWrapper(localName = "BinnatsiResponse",
        targetNamespace = "http://cixs.test.legstar.com/binnatsi",
        className = "com.legstar.test.cixs.binnatsi.BinnatsiResponse")
    com.legstar.test.coxb.binnatsi.DfhcommareaType binnatsi(
        @WebParam(name = "Request",
               targetNamespace = "http://cixs.test.legstar.com/binnatsi")
        com.legstar.test.coxb.binnatsi.DfhcommareaType request,
        @WebParam(name = "HostHeader", header = true, partName = "HostHeader",
                targetNamespace = "http://cixs.test.legstar.com/binnatsi")
        BinnatsiHostHeader hostHeader)
        throws BinnatsiFault;

}

