
package com.legstar.test.cixs.redbotha;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RedbothaFaultInfo", targetNamespace = "http://cixs.test.legstar.com/redbotha")
public class RedbothaFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RedbothaFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RedbothaFault(String message, RedbothaFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RedbothaFault(String message, RedbothaFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.legstar.test.cixs.redbotha.RedbothaFaultInfo
     */
    public RedbothaFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
