//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.05 at 10:40:56 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://legstar.com/mq/mqcih", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.legstar.mq.mqcih;
