
package com.legstar.test.cixs.binpkdus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "binpkdusPort", targetNamespace = "http://cixs.test.legstar.com/binpkdus")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.legstar.test.coxb.binpkdus.ObjectFactory.class,
    com.legstar.test.cixs.binpkdus.ObjectFactory.class
})
public interface BinpkdusPort {


    /**
     * 
     * @param hostHeader
     * @param parameters
     * @return
     *     returns com.legstar.test.cixs.binpkdus.BinpkdusResponse
     * @throws BinpkdusFault
     */
    @WebMethod
    @WebResult(name = "BinpkdusResponse", targetNamespace = "http://cixs.test.legstar.com/binpkdus", partName = "result")
    public BinpkdusResponse binpkdus(
        @WebParam(name = "BinpkdusRequest", targetNamespace = "http://cixs.test.legstar.com/binpkdus", partName = "parameters")
        BinpkdusRequest parameters,
        @WebParam(name = "HostHeader", targetNamespace = "http://cixs.test.legstar.com/binpkdus", header = true, partName = "HostHeader")
        BinpkdusHostHeader hostHeader)
        throws BinpkdusFault
    ;

}
