/*******************************************************************************
 * LegStar legacy Web-enablement .
 * Copyright (C)  2007 LegSem
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301  USA
 * 
 *     
 *****************************************************************************/

package com.legstar.test.cixs.osarrays;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-01/26/2007 12:09 AM(kohsuke)-RC2
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "osarraysService", targetNamespace = "http://cixs.test.legstar.com/osarrays", wsdlLocation = "http://localhost:8080/cixs-osarrays/osarrays?wsdl")
public class OsarraysService
    extends Service
{

    private final static URL OSARRAYSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cixs-osarrays/osarrays?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        OSARRAYSSERVICE_WSDL_LOCATION = url;
    }

    public OsarraysService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OsarraysService() {
        super(OSARRAYSSERVICE_WSDL_LOCATION, new QName("http://cixs.test.legstar.com/osarrays", "osarraysService"));
    }

    /**
     * 
     * @return
     *     returns OsarraysPort
     */
    @WebEndpoint(name = "OsarraysImplPort")
    public OsarraysPort getOsarraysImplPort() {
        return (OsarraysPort)super.getPort(new QName("http://cixs.test.legstar.com/osarrays", "OsarraysImplPort"), OsarraysPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OsarraysPort
     */
    @WebEndpoint(name = "OsarraysImplPort")
    public OsarraysPort getOsarraysImplPort(WebServiceFeature... features) {
        return (OsarraysPort)super.getPort(new QName("http://cixs.test.legstar.com/osarrays", "OsarraysImplPort"), OsarraysPort.class, features);
    }

}
